name: mix_stack
description: MixStack lets you connects Flutter smoothly with existing Native codebase without headache.
version: 1.0.6
homepage: https://github.com/yuewen/mix_stack

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.yuewen.mix_stack
        pluginClass: MixStackPlugin
      ios:
        pluginClass: MixStackPlugin